### ISSUE TITLE
This plugin seems to be removed from npm

### ISSUE THREAD

**Issue by VasilyStrelyaev** [Shafied/testcafe-reporter-slack#1]
Hi @Shafied ,

My name is Vasily and I work for the TestCafe core team.
Thank you for creating this awesome plugin. We have tested it and it works great.
We would like to promote it to our users, mention it in the documentation and on the website.

However, it seems like you removed the package from npm. I believe there was a strong reason behind this decision. Nevertheless, may I ask you to republish it so that more people could benefit from your work.

Thanks in advance!

**Comment by Shafied** [comment]
Hi Vasily,

I removed the package from npm because I used some business information
that shouldn't be public. I'll remove the info from my repo and will
republish it somewhere this week. I will mail you when I have republished
the repo.

Op wo 19 jul. 2017 11:47 schreef Vasily Strelyaev <notifications@github.com

**Comment by VasilyStrelyaev** [comment]
Thanks a lot!
